### ISSUE TITLE
500 error - searching for lemmy user

### ISSUE THREAD

**Issue by whatSocks** [jointakahe/takahe#202] opened 2022-12-19 01:59 UTC
* searching for a nonexisting user (example:@Kfdulun@mandeddr.xyzfda)  fails gracefully 
* searching for lemmy user copy+pasted from lemmy throws 500 -  (grab any from https://mander.xyz/) 

<img width="958" alt="image" src="https://user-images.githubusercontent.com/2731744/208333381-859fab4e-ce58-4cad-b931-e969124b33a9.png">

**Comment by TkTech** [comment] 2022-12-19 04:11
```
('Invalid JSON-LD syntax; a term definition must not contain type',)
Type: jsonld.SyntaxError
Code: invalid term definition
Details: {'context': {'stickied': 'as:stickied', 'pt': 'https://join-lemmy.org#', 'sc': 'http://schema.org#', 'matrixUserId': {'type': 'sc:Text', 'id': 'as:alsoKnownAs'}, 'sensitive': 'as:sensitive', 'comments_enabled': {'type': 'sc:Boolean', 'id': 'pt:commentsEnabled'}, 'moderators': 'as:moderators'}}
```

**Comment by manfre** [comment] 2022-12-19 04:47
Bug is us not gracefully handling the LD error.

**Comment by manfre** [comment] 2022-12-19 04:49
Dupe of #180

**Closed by manfre** 2022-12-19 04:49 UTC
Labels: bug, area/activitypub
