### ISSUE TITLE
Option to use WebAuthn for authentication

### ISSUE THREAD

**Issue by okpierre** [jointakahe/takahe#395] opened 2023-01-11 11:45 UTC
Admin can choose to enable/disable WebAuthn for each of their instances

"The FIDO Alliance developed FIDO Authentication standards based on public key cryptography for authentication that is more secure than passwords and SMS OTPs, simpler for consumers to use, and easier for service providers to deploy and manage. FIDO Authentication enables password-only logins to be replaced with secure and fast login experiences across websites and apps."

https://fidoalliance.org/fido2/

**Comment by andrewgodwin** [comment] 2023-01-11 16:14
I agree, but this is a duplicate of #390

**Closed by andrewgodwin** 2023-01-11 16:14 UTC
Labels: res/duplicate
