### ISSUE TITLE
500 error - initial search for post with an emojo

### ISSUE THREAD

**Issue by whatSocks** [jointakahe/takahe#205] opened 2022-12-19 02:21 UTC
this one is hard to reproduce. It was happening consistently, then seemed to fix itself

* first, find a post on the fediverse with an emojo that your takahe server doesn't know about yet (search #emojo on your mastodon server for example)
* paste the URL of the post in takahe search
* see 500 error
* go back to search, search same post again
* now it works

**Comment by andrewgodwin** [comment] 2022-12-19 11:26
Ooh, I bet we don't finish fetching the emoji before we render it or something. Thanks for the hint - I should be able to reproduce from this!

**Comment by andrewgodwin** [comment] 2022-12-19 11:42
Going through the sentry, pretty sure this might be the culprit:

```
AttributeError
'NoneType' object has no attribute 'local'

activities/models/emoji.py in by_ap_tag at line 247

        shortcode = data["name"].lower().strip(":")
        icon = data["icon"]
        category = (icon.get("category") or "")[:100]
        emoji = cls.objects.create(
            shortcode=shortcode,
            domain=None if domain.local else domain,
```

**Comment by andrewgodwin** [comment] 2022-12-20 10:19
Dupe of #190 in the end

**Closed** 2022-12-20 10:18 UTC
Labels: bug, area/activitypub, area/posts
